import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TransitionProvider } from "@/components/TransitionContext";
import InitialLoaderWrapper from "@/components/InitialLoaderWrapper";
import DynamicTabHeader from "@/components/DynamicTabHeader"; // 1. Import เข้ามา

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 2. เรียกใช้งาน DynamicTabHeader ที่นี่ */}
        <DynamicTabHeader />

        <InitialLoaderWrapper>
          <TransitionProvider>
            {children}
          </TransitionProvider>
        </InitialLoaderWrapper>
      </body>
    </html>
  );
}